version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - spark-net

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - spark-net

  spark-master:
    image: bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    networks:
      - spark-net

  spark-worker:
    image: bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-app-main:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    depends_on:
      - kafka
      - spark-master
      - spark-worker
    networks:
      - spark-net

  spark-app-jobs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - kafka
      - spark-master
      - spark-worker
    networks:
      - spark-net

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: spark-jupyter
    ports:
      - "8899:8888"
    volumes:
      - ./data:/data
      - ./app:/app
      - ./notebooks:/home/jovyan/work

networks:
  spark-net:
    driver: bridge
