[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python app/main.py"
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8080"
SPARK_MASTER = "local[*]"
KAFKA_BROKERS = "localhost:9092"
