[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

# CORREGIR: Cambiar el startCommand
[deploy]
startCommand = "docker compose -f docker-compose.prod.yml up -d"
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8080"
SPARK_MASTER = "local[*]"
KAFKA_BROKERS = "localhost:9092"
